# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'TICDemo' do
  pod 'TEduBoard_iOS',:podspec=>'https://sdk.qcloudtiw.com/ios/2.7.3.119/TEduBoard_iOS.podspec'
#  pod 'TEduBoard_iOS'
  pod 'TXIMSDK_Plus_iOS', '6.2.2363'
end
