# Uncomment the next line to define a global platform for your project
platform :macos, '10.10'

target 'TICDemo_Mac' do
  pod 'TEduBoard_Mac','2.5.0.8'
  pod 'TXIMSDK_Mac','4.6.101'
  pod 'TXLiteAVSDK_TRTC_Mac','6.9.8341'
  pod 'SDWebImage'
end
